# Generated by Django 4.1.5 on 2023-01-03 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("caballos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Jinete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("apellido", models.CharField(max_length=50)),
                ("fecha_nacimiento", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Equitacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "caballo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="caballos.caballo",
                    ),
                ),
                (
                    "jinete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jinetes.jinete"
                    ),
                ),
            ],
        ),
    ]
