# Generated by Django 4.1.5 on 2023-01-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Caballo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("fecha_nacimiento", models.DateTimeField(blank=True, null=True)),
                ("anio_muerte", models.IntegerField(blank=True, null=True)),
                ("datos_generales", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
