# Generated by Django 4.1.5 on 2023-01-03 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jinetes", "0001_initial"),
        ("caballos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="caballo",
            name="jinete_principal",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="jinetes.jinete",
            ),
        ),
    ]
