# Generated by Django 4.1.5 on 2023-01-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caballos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="caballo",
            name="edad",
            field=models.IntegerField(default=30),
        ),
    ]
